### ISSUE TITLE
Can't set feature-state on Source w. generateId

### ISSUE THREAD

**Issue by garretteklof** [dimapio/map-gl#6]
Console error `Attempted to set the feature state of a feature with no ID` on Layer with case statement in `paint` for a Source with `generateId: true`.

Note: when logging the feature in HoverPopup, the `id` is in fact generated:
<img width="311" alt="Screenshot 2024-09-26 at 5 20 44 PM" src="https://github.com/user-attachments/assets/14413316-a680-4ee5-aa44-dbe6274c189f">
<img width="675" alt="Screenshot 2024-09-26 at 5 20 33 PM" src="https://github.com/user-attachments/assets/5cd5635c-1a77-40d4-9969-f19f35ebf6bb">

The `paint` statement is not executed (e.g. change in fill-color) and error leads to believe that `mapbox-gl` is never properly updated with the feature state.

(`promoteId` does not seem to work either, in this specific case it'd be `promoteId: 'Id'`)

**Comment by nsiebenaller** [comment]
@garretteklof I can't reproduce this issue, however, I found another issue relating to the map not loading sources/layers on initial load. I pushed a fix to `canary` - can you test again using that?

Otherwise I'll need a link to the code you're working on.

**Comment by garretteklof** [comment]
I pulled and unfortunately it does not seem to resolve the `feature-state` issue.

The platform code can be accessed [here.](https://github.com/dimapio/platform) It's right now the `/demo` page.

**Comment by nsiebenaller** [comment]
@garretteklof I see the problem. When the layer checks if a GeoJSON feature has an id it uses a falsey check. Since `0` is a falsey value it triggers the "feature does not have id" warning.

https://github.com/dimapio/map-gl/blob/69d04e685e3bc2bdcb25fedbbe7006d473e893da/src/components/Layer.tsx#L56-L69

**Comment by nsiebenaller** [comment]
@garretteklof Additionally, I think it would help to improve this console warning for better DX. I've opened https://github.com/dimapio/map-gl/issues/10 to improve this warning.
